"""
main.py — Entry point to kick off the AI Investigative Journalist system.

Initialises the JournalistState with a research topic, streams the execution
of the LangGraph (Orchestrator -> Tools -> Procurement -> Execution -> Audit),
and prints the output so we can see the micro-payments in action.
"""

from graph import app
from state import JournalistState


def main():
    # 1. Define the topic the AI agent needs to research
    topic = "The Financial Network Behind Apex Holdings"
    
    print(f"🎬 Starting investigation on: '{topic}'")
    print("-" * 50)
    
    # 2. Initialize the state
    initial_state = JournalistState(
        topic=topic,
        draft_content="",
        payment_required=False,
        invoice_details={},
        access_token=None,
        payment_approved=False,
        payment_attempts=0,
        messages=[]
    )
    
    # 3. Compile configuration (thread_id is useful if we want to save state later)
    config = {"configurable": {"thread_id": "1"}}
    
    # 4. Stream the graph execution to watch the agents work
    for output in app.stream(initial_state, config, stream_mode="updates"):
        for node_name, state_update in output.items():
            print(f"\n✅ [Node Executed]: {node_name}")
            
            # Print any new messages generated by this node
            if "messages" in state_update:
                for msg in state_update["messages"]:
                    content = msg.content
                    # Truncate content for cleaner console output
                    if len(content) > 150:
                        content = content[:150] + "... [truncated]"
                    print(f"  💬 {msg.__class__.__name__}: {content}")
                    
            # Print crucial state changes
            if "payment_required" in state_update and state_update["payment_required"]:
                invoice = state_update.get("invoice_details", {})
                print(f"  🚨 PAYWALL HIT! Invoice: {invoice}")
            
            if "payment_approved" in state_update:
                print(f"  💼 Procurement Decision: {'APPROVED' if state_update['payment_approved'] else 'DENIED'}")
                
            if "access_token" in state_update and str(state_update["access_token"]).startswith("0x"):
                print(f"  🔗 Tx Hash (Proof of Payment): {state_update['access_token']}")

    print("\n" + "=" * 50)
    print("🎯 Execution Complete. Check 'compliance_audit_log.md' for the report.")


if __name__ == "__main__":
    main()
