/**
 * audit.ts — Audit Trail Agent Node for the Seller LangGraph.
 *
 * This is the FINAL node in the seller's agentic flow:
 *   broker_pricing → settlement_agent → packager_agent → audit_agent → END
 *
 * It logs every transaction (successful or denied) into a rich Markdown
 * audit trail file (`seller_audit_log.md`), mirroring the buyer's audit.py.
 *
 * Captures: article metadata, broker price, settlement status, packager
 * outcome, and a timestamped event record for compliance.
 */

import fs from 'fs';
import path from 'path';

const AUDIT_LOG_PATH = path.join(__dirname, 'seller_audit_log.md');

/**
 * LangGraph node — generates and appends a Markdown audit report.
 */
export const auditTransaction = async (state: any) => {
  console.log("---> [LangGraph] Entering 'audit_agent' node...");

  // ── Extract state ──────────────────────────────────────────────────
  const articleData = state.articleData || {};
  const price = state.price ?? 0;
  const settlementStatus = state.settlementStatus || "unknown";
  const paymentOptions = state.paymentOptions || {};
  const packagedResponse = state.packagedResponse || {};

  const timestamp = new Date().toISOString();
  const articleId = articleData.id || "unknown";
  const articleTitle = articleData.title || "Untitled";

  // ── Determine outcome indicators ──────────────────────────────────
  let statusEmoji: string;
  let outcomeLabel: string;

  switch (settlementStatus) {
    case "verified":
      statusEmoji = "🟢";
      outcomeLabel = "Payment Verified — Data Delivered";
      break;
    case "requires_payment":
      statusEmoji = "🔴";
      outcomeLabel = "Payment Required — Access Denied";
      break;
    default:
      statusEmoji = "⚪";
      outcomeLabel = `Status: ${settlementStatus}`;
  }

  const deliveryStatus = packagedResponse?.status === 200
    ? "✅ Delivered"
    : `❌ Not Delivered (${packagedResponse?.status || "N/A"})`;

  // ── Build Markdown report ─────────────────────────────────────────
  const mdLines = [
    `## 📋 Seller Audit Log Entry`,
    `**Timestamp:** ${timestamp}`,
    `**Article:** ${articleTitle} (\`${articleId}\`)`,
    ``,
    `### 💰 Transaction Summary`,
    `| Metric | Value |`,
    `| :--- | :--- |`,
    `| **Broker Price** | $${price.toFixed(2)} USD |`,
    `| **Settlement** | ${statusEmoji} ${outcomeLabel} |`,
    `| **Data Delivery** | ${deliveryStatus} |`,
    `| **Network** | ${paymentOptions?.network || "N/A"} |`,
    `| **Pay-To Wallet** | \`${paymentOptions?.payTo || "N/A"}\` |`,
    ``,
    `### ⏱️ Agent Pipeline`,
    `- **Broker Pricing** → Set price at $${price.toFixed(2)}`,
    `- **Settlement Agent** → ${settlementStatus}`,
    `- **Packager Agent** → ${deliveryStatus}`,
    `- **Audit Agent** → Log recorded`,
    ``,
    `---`,
    ``,
  ];

  const report = mdLines.join("\n");

  // ── Append to audit log file ──────────────────────────────────────
  try {
    // Create file with header if it doesn't exist
    if (!fs.existsSync(AUDIT_LOG_PATH)) {
      const header = [
        `# 🏛️ Seller-Side Audit Trail`,
        `> Auto-generated by the Audit Agent in the Seller LangGraph.`,
        `> Each entry represents one content access request.`,
        ``,
        `---`,
        ``,
      ].join("\n");
      fs.writeFileSync(AUDIT_LOG_PATH, header, "utf8");
    }

    fs.appendFileSync(AUDIT_LOG_PATH, report, "utf8");
    console.log(`📝 [Audit] Log entry written for "${articleTitle}"`);
  } catch (err: any) {
    console.error(`❌ [Audit] Failed to write log: ${err.message}`);
  }

  // Return empty update — audit is a terminal side-effect node
  return {};
};
